spring.application.name=CarsMicroservice
server.servlet.context-path=/api/cars

spring.datasource.url=jdbc:postgresql://localhost:5432/carsmicrodb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.hiddenmethod.filter.enabled=true