spring.application.name=UsersMicroservice
server.port=8081
SECRET_KEY=UmF1bEVzdGVTbWVjaGVyU2lBY2Vhc3RhUGFyb2xhRXN0ZUZvYXJ0ZUdyZXVEZVNwYXJ0Cg==
EXPIRATION_MS=86400000
internal.secret=very-strong-secret
spring.datasource.url=jdbc:postgresql://localhost:5432/usersmicrodb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update